//! Live generation against a real stable-diffusion.cpp `sd-server` (Task 10). Ignored by default.
//!
//! ```bash
//! MCP_IMAGEGEN_SD_SERVER=~/path/to/sd-server \
//! MCP_IMAGEGEN_LIVE_MODEL=qwen-image-2.1 \
//!   cargo test --release --test sdcpp_live -- --ignored --nocapture
//! ```
//!
//! Uses the example registry and the real Hugging Face cache. Generates the same seed twice at a
//! small size and checks the pixels match, then prints timings for docs/benchmarks.md.
#![cfg(feature = "sdcpp")]

use std::collections::BTreeMap;
use std::sync::Arc;
use std::time::{Duration, Instant};

use mcp_imagegen::backend::BackendRegistry;
use mcp_imagegen::backend::sdcpp::SdcppBackend;
use mcp_imagegen::config::{Config, MODELS_EXAMPLE, default_hf_cache, expand_tilde};
use mcp_imagegen::jobs::{JobConfig, JobManager, JobRequest, JobStatus};
use mcp_imagegen::registry::ModelRegistry;
use mcp_imagegen::request::GenerateRequest;

fn env_or(key: &str, default: &str) -> String {
    std::env::var(key).unwrap_or_else(|_| default.to_string())
}

#[tokio::test]
#[ignore = "needs sd-server and model weights; run manually"]
async fn same_seed_reproduces_pixels() {
    let model_id = env_or("MCP_IMAGEGEN_LIVE_MODEL", "qwen-image-2.1-turbo");
    let size: u32 = env_or("MCP_IMAGEGEN_LIVE_SIZE", "512").parse().unwrap();
    let server_bin = expand_tilde(&env_or("MCP_IMAGEGEN_SD_SERVER", "sd-server"));

    let out = tempfile::tempdir().unwrap();
    let cfg_text = format!(
        "default_output_dir = {o:?}\nallowed_output_roots = [{o:?}]\n[backends.sdcpp]\nserver_bin = {b:?}\nstartup_timeout_secs = 600\n",
        o = out.path().to_str().unwrap(),
        b = server_bin.to_str().unwrap(),
    );
    let cfg = Config::from_toml(out.path(), &cfg_text).unwrap();
    let registry = ModelRegistry::from_toml(MODELS_EXAMPLE).unwrap();
    let model = registry.get(&model_id).unwrap().clone();
    let files = model
        .resolve_files(&default_hf_cache())
        .unwrap_or_else(|missing| {
            panic!(
                "missing weights: {}",
                missing
                    .iter()
                    .map(|m| m.fetch_hint())
                    .collect::<Vec<_>>()
                    .join(" && ")
            )
        });

    let mut backends = BackendRegistry::default();
    backends.insert(Arc::new(SdcppBackend::new(cfg.sdcpp.clone())));
    let jobs = JobManager::new(
        backends,
        JobConfig {
            max_queue: 4,
            job_ttl: Duration::from_secs(3600),
            idle_unload: Duration::from_secs(3600),
        },
    );

    let request = GenerateRequest {
        prompt: "a weathered wooden supply crate with iron corner brackets, studio lighting, game asset concept".into(),
        model: Some(model_id.clone()),
        width: Some(size),
        height: Some(size),
        seed: Some(1234),
        wait: true,
        ..Default::default()
    };
    let (mut resolved, _) = request.resolve(&registry).unwrap();
    resolved.loras = model.resolve_loras(&default_hf_cache()).unwrap_or_default();

    let mut images = Vec::new();
    for run in 1..=2 {
        let started = Instant::now();
        let snap = jobs
            .submit(JobRequest {
                model: model.clone(),
                files: files.clone(),
                request: resolved.clone(),
                output: out.path().join(format!("live-{run}.png")),
                want_preview: false,
            })
            .unwrap();
        let done = jobs.wait(&snap.job_id).await.unwrap();
        assert_eq!(done.status, JobStatus::Done, "run {run}: {:?}", done.error);
        let result = done.result.unwrap();
        println!(
            "run {run}: {model_id} {size}x{size} steps={} wall={:.1}s timings={}",
            resolved.steps,
            started.elapsed().as_secs_f64(),
            serde_json::to_string(&result.record.timings).unwrap()
        );
        assert!(result.sidecar_path.exists());
        let sidecar: BTreeMap<String, serde_json::Value> =
            serde_json::from_slice(&std::fs::read(&result.sidecar_path).unwrap()).unwrap();
        assert_eq!(sidecar["seed"], 1234);
        assert_eq!(sidecar["model"], model_id.as_str());
        images.push(image::open(&result.path).unwrap().to_rgb8());
    }
    assert_eq!(images[0].dimensions(), (size, size));
    assert!(
        images[0].as_raw() == images[1].as_raw(),
        "same seed produced different pixels"
    );
    jobs.unload_all().await.unwrap();
}

/// Edit an image: same seed + same input must give identical pixels.
/// Input: MCP_IMAGEGEN_LIVE_EDIT_INPUT, or (default) a source image generated by this test first.
#[tokio::test]
#[ignore = "needs sd-server, model weights and vision weights; run manually"]
async fn edit_same_seed_reproduces_pixels() {
    use mcp_imagegen::input::InputPolicy;
    use mcp_imagegen::request::{EditRequest, Mode};

    let model_id = env_or("MCP_IMAGEGEN_LIVE_MODEL", "qwen-image-2.1-turbo");
    let size: u32 = env_or("MCP_IMAGEGEN_LIVE_SIZE", "512").parse().unwrap();
    let server_bin = expand_tilde(&env_or("MCP_IMAGEGEN_SD_SERVER", "sd-server"));
    let out = tempfile::tempdir().unwrap();
    let input = out.path().join("source.png");
    let provided = std::env::var("MCP_IMAGEGEN_LIVE_EDIT_INPUT").ok();
    let cfg_text = format!(
        "default_output_dir = {o:?}\nallowed_output_roots = [{o:?}]\n[backends.sdcpp]\nserver_bin = {b:?}\nstartup_timeout_secs = 600\n",
        o = out.path().to_str().unwrap(),
        b = server_bin.to_str().unwrap(),
    );
    let cfg = Config::from_toml(out.path(), &cfg_text).unwrap();
    let registry = ModelRegistry::from_toml(MODELS_EXAMPLE).unwrap();
    let model = registry.get(&model_id).unwrap().clone();
    let mut files = model
        .resolve_files(&default_hf_cache())
        .expect("base weights");
    let edit_files = model
        .resolve_edit_files(&default_hf_cache())
        .unwrap_or_else(|m| panic!("missing edit weights: {}", m[0].fetch_hint()));
    files.extend(edit_files);

    let mut backends = BackendRegistry::default();
    backends.insert(Arc::new(SdcppBackend::new(cfg.sdcpp.clone())));
    let jobs = JobManager::new(
        backends,
        JobConfig {
            max_queue: 4,
            job_ttl: Duration::from_secs(3600),
            idle_unload: Duration::from_secs(3600),
        },
    );
    let policy = InputPolicy {
        base_dir: out.path().to_path_buf(),
        allowed_roots: vec![out.path().to_path_buf()],
        max_bytes: cfg.max_input_bytes,
        max_side: cfg.max_input_side,
    };
    match provided {
        Some(path) => {
            std::fs::copy(expand_tilde(&path), &input).expect("MCP_IMAGEGEN_LIVE_EDIT_INPUT");
        }
        None => {
            // Make the source with the same model.
            let (src_req, _) = GenerateRequest {
                prompt:
                    "a weathered wooden supply crate with iron corner brackets, studio lighting"
                        .into(),
                model: Some(model_id.clone()),
                width: Some(size),
                height: Some(size),
                seed: Some(1234),
                wait: true,
                ..Default::default()
            }
            .resolve(&registry)
            .unwrap();
            let mut src_req = src_req;
            src_req.loras = model.resolve_loras(&default_hf_cache()).unwrap_or_default();
            let snap = jobs
                .submit(JobRequest {
                    model: model.clone(),
                    files: files.clone(),
                    request: src_req,
                    output: input.clone(),
                    want_preview: false,
                })
                .unwrap();
            let done = jobs.wait(&snap.job_id).await.unwrap();
            assert_eq!(done.status, JobStatus::Done, "source: {:?}", done.error);
        }
    }
    let request = EditRequest {
        images: vec![input.to_string_lossy().into()],
        params: GenerateRequest {
            prompt:
                "paint the crate bright red, keep the dark iron corner brackets and the wood grain"
                    .into(),
            model: Some(model_id.clone()),
            width: Some(size),
            height: Some(size),
            seed: Some(4321),
            wait: true,
            ..Default::default()
        },
    };
    let (mut resolved, _) = request.resolve(&registry, &policy).unwrap();
    resolved.loras = model.resolve_loras(&default_hf_cache()).unwrap_or_default();
    assert_eq!(resolved.mode, Mode::Edit);

    let mut images = Vec::new();
    for run in 1..=2 {
        let started = Instant::now();
        let snap = jobs
            .submit(JobRequest {
                model: model.clone(),
                files: files.clone(),
                request: resolved.clone(),
                output: out.path().join(format!("edit-{run}.png")),
                want_preview: false,
            })
            .unwrap();
        let done = jobs.wait(&snap.job_id).await.unwrap();
        assert_eq!(done.status, JobStatus::Done, "run {run}: {:?}", done.error);
        let result = done.result.unwrap();
        println!(
            "edit run {run}: {model_id} {size}x{size} steps={} wall={:.1}s timings={} out={}",
            resolved.steps,
            started.elapsed().as_secs_f64(),
            serde_json::to_string(&result.record.timings).unwrap(),
            result.path.display()
        );
        let keep = std::env::var("MCP_IMAGEGEN_LIVE_KEEP_DIR").ok();
        if let Some(dir) = keep {
            let dest = expand_tilde(&dir).join(format!(
                "qwen21-edit-red-crate-{size}-seed4321-run{run}.png"
            ));
            std::fs::copy(&result.path, &dest).unwrap();
            std::fs::copy(&result.sidecar_path, dest.with_extension("json")).unwrap();
        }
        assert_eq!(result.record.references.len(), 1);
        images.push(image::open(&result.path).unwrap().to_rgb8());
    }
    assert_eq!(images[0].dimensions(), (size, size));
    assert!(
        images[0].as_raw() == images[1].as_raw(),
        "same seed + input produced different pixels"
    );
    jobs.unload_all().await.unwrap();
}
